name: Laravel Pint
on: pull_request
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v3
      - name: "Running laravel-pint"
        uses: aglipanci/laravel-pint-action@2.2.0
        with:
          preset: laravel
          verboseMode: true
          onlyDirty: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply pint changes
          commit_options: '--no-verify'
          file_pattern: '*.php'
